##  Numpy array and basics
Learn about numpay with chai aur code  

In [1]:
import numpy as np

### creating arry from list

In [4]:
arr_id = np.array([1,2,3,4,5])

print("1D array ",arr_id)

arr_2 = np.array([[1,2,3,4],[5,6,7,8]])
print("2D array ",arr_2)


1D array  [1 2 3 4 5]
2D array  [[1 2 3 4]
 [5 6 7 8]]


### list vs numpy array  

In [6]:
py_list1 = [1,2,3,4,5]
print("python list multiplication ",py_list1 * 2)

numpy_arr1 = np.array([1,2,3])
print("python list multiplication ",numpy_arr1 * 2)

import time 

start_time = time.time()

py_list = [i * 2 for i in range(10000000)]
print("\n python  List time ", time.time() - start_time)

start_time = time.time()

numpy_arr = np.arange(10000000)
print("\n python  List time ", time.time() - start_time)


python list multiplication  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
python list multiplication  [2 4 6]

 python  List time  5.710797548294067

 python  List time  0.03581881523132324


## creating array from scratch 

In [14]:
zeros_array = np.zeros((3,4))
print(" zerros array \n", zeros_array)


ones_array = np.ones((2,3))
print(" ones array \n", ones_array)

full_array = np.full((2,3),7)
print(" constant array \n", full_array)

random_array = np.random.random((2,3))
print(" random array \n", random_array)

sequance_array = np.arange(0,10,2)
print(" sequence \n", sequance_array)





 zerros array 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 ones array 
 [[1. 1. 1.]
 [1. 1. 1.]]
 constant array 
 [[7 7 7]
 [7 7 7]]
 random array 
 [[0.55588862 0.81003883 0.44796988]
 [0.51645089 0.75880054 0.92905647]]
 sequence 
 [0 2 4 6 8]


### vactor , Matrix, Tensor

In [17]:
vector = np.array([1,2,3])
print("Vector \n", vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix \n", matrix)

tensor = np.array([[[1,2,3],[7,8,9]],[[4,5,6],[1,2,3]]])
print("Tenser \n", tensor)



Vector 
 [1 2 3]
Matrix 
 [[1 2 3]
 [4 5 6]]
Tenser 
 [[[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [1 2 3]]]


## Array Properties

In [19]:
arr_prop = np.array([[1,2,3],[4,5,6]])

print("Shape ", arr_prop.shape)
print("Dimension ", arr_prop.ndim)
print("Size ", arr_prop.size)
print("Data Type ", arr_prop.dtype)

Shape  (2, 3)
Dimension  2
Size  6
Data Type  int64


### Array Reshapping

In [23]:
arr_res = np.arange(12)
print("Oraginal array ", arr_res)

reshaped = arr_res.reshape((4,3))
print("Reshaped Array ", reshaped)

flattered_array = reshaped.flatten()
print("Flattered \n", flattered_array)

#  revel (returns view , insted of copy)

raveled = reshaped.ravel()
print("Raveled Array \n", raveled)

#  transpose 
transpose = reshaped.T
print("Transpose \n", transpose)



Oraginal array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Flattered 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose 
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
